name: moneyku
description: project version 1.0.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # carousel_slider
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  # google_font
  google_fonts: ^6.0.1
    # flutter charts
  fl_chart: ^0.60.0  
  #lottie
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/lotties/


