import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

Color kWhiteColor = const Color(0xffFFFFFF);
Color kBlackSoftColor = const Color(0xff2E2F31);
Color kBlackColor = const Color(0xff000000);
Color kGrayColor = const Color(0xffA4A8AE);
Color kGray2Color = const Color(0xff696B76);
Color kGraySoftColor = const Color(0xffF1F1F9);
Color kLightBackgraundColor = const Color(0xffF6F8FB);
Color kDarkBackgraundColor = const Color(0xff1B1C1E);
Color kDarkSoftBackgraundColor = const Color(0xff07070B);
Color kGrayBackgraundColor = const Color(0xff575861);
Color kPurpleColor = const Color(0xff695BE9);
Color kBlueColor = const Color(0xff052554);
Color kBlueAccerColor = const Color(0xff007FFF);
Color kBlueAccer2Color = const Color(0xff007FFF);
Color kBlueDarkColor = const Color(0xff0034C4);
Color kNumberBackgroundColor = const Color(0xff1A1D2E);
Color kRedColor = const Color(0xffFF2566);
Color kGreenColor = const Color(0xff22B07D);
Color kYellowColor = const Color(0xffFFDF34);
Color kYellowDarkColor = const Color(0xffFBB600);
Color kOrangeColor = const Color(0xffF87000);
Color kOrangeSoftColor = const Color(0xffF94B01);

TextStyle blackTextStyle = GoogleFonts.poppins(color: kBlackColor);
TextStyle grayTextStyle = GoogleFonts.poppins(color: kGrayColor);
TextStyle graydarkTextStyle = GoogleFonts.poppins(color: kGray2Color);
TextStyle graySoftTextStyle = GoogleFonts.poppins(color: kGraySoftColor);
TextStyle whiteTextStyle = GoogleFonts.poppins(color: kWhiteColor);
TextStyle blueTextStyle = GoogleFonts.poppins(color: kBlueColor);
TextStyle greenTextStyle = GoogleFonts.poppins(color: kGreenColor);
TextStyle purpleTextStyle = GoogleFonts.poppins(color: kPurpleColor);
TextStyle yellowTextStyle = GoogleFonts.poppins(color: kYellowDarkColor);
TextStyle redTextStyle = GoogleFonts.poppins(color: kRedColor);
TextStyle orangeTextStyle = GoogleFonts.poppins(color: kOrangeSoftColor);

FontWeight light = FontWeight.w300;
FontWeight regular = FontWeight.w400;
FontWeight medium = FontWeight.w500;
FontWeight semiBold = FontWeight.w600;
FontWeight bold = FontWeight.w700;
FontWeight extraBold = FontWeight.w800;
FontWeight black = FontWeight.w900;
